# Generated by Django 4.2.5 on 2023-10-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTHREE_RI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Phone_number',
            new_name='Rating',
        ),
    ]
